package com.example.util

/**
 * Global constants for ScanPro app configuration, update repositories,
 * sharing URLs, and storage persistence keys.
 */
object Constants {
    // GitHub Repository & Release Configuration
    const val GITHUB_REPO = "Rony-Mia/ScanPro"
    const val GITHUB_RELEASES_PAGE = "https://github.com/$GITHUB_REPO/releases/latest"
    const val GITHUB_LATEST_API = "https://api.github.com/repos/$GITHUB_REPO/releases/latest"
    
    // Direct link to the latest release APK artifact generated by CI workflow
    // (build_apk.yml uploads app-debug.apk / app-release.apk to GitHub Releases)
    const val LATEST_APK_DOWNLOAD_URL = "https://github.com/$GITHUB_REPO/releases/latest/download/app-debug.apk"
    
    // Standard promotional message template for sharing the app
    const val SHARE_APP_MESSAGE = "Check out ScanPro — scan, merge, and manage documents, free and offline!\nDownload: $LATEST_APK_DOWNLOAD_URL"
    const val SHARE_CHOOSER_TITLE = "Share ScanPro via"

    // Storage and Preferences
    const val PREFS_NAME = "scanpro_prefs"
    const val PREF_KEY_ONBOARDING_COMPLETED = "is_onboarding_completed"
    
    const val PREF_KEY_SAVE_LOCATION_MODE = "pref_save_location_mode"
    const val PREF_KEY_CUSTOM_FOLDER_URI = "pref_custom_folder_uri"
    const val PREF_KEY_CUSTOM_FOLDER_NAME = "pref_custom_folder_name"
    
    const val DEFAULT_SAVE_LOCATION_NAME = "Documents/ScanPro"
    const val SAVE_LOCATION_MODE_DEFAULT = "DEFAULT"
    const val SAVE_LOCATION_MODE_CUSTOM = "CUSTOM"
}
